# Generated by Django 3.2.9 on 2021-12-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EvaluationAPI', '0003_auto_20211206_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stadiumavailabililty',
            old_name='free_slots_send_time',
            new_name='free_slots_end_time',
        ),
    ]
