# Generated by Django 3.2.9 on 2021-12-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvaluationAPI', '0004_rename_free_slots_send_time_stadiumavailabililty_free_slots_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadiumavailabililty',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='stadiumavailabililty',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stadiumavailabililty',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
