# Generated by Django 3.2.9 on 2021-12-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EvaluationAPI', '0005_auto_20211206_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='stadiumavailabililty',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
